<?php

class Page
{
    public $content;
    public $title = "Devian Conslulting LLC";
    public $keywords = "Devian Consulting, Six Letter Abbreviation, some of my best friends are search engines";
    public $navigation_buttons = array("Home" => "home.php",
                                        "Contact" => "contact.php",
                                        "Services" => "services.php",
                                        "Site Map" => "map.php"
                                        );
}